language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t jemmy239/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true jemmy239/docker-react npm run test -- --coverage